version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pg-archive
    environment:
      POSTGRES_USER: pg-user
      POSTGRES_PASSWORD: pg-pwd
      POSTGRES_DB: archive
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: