# Use postgres/example user/password credentials
version: '3.9'

services:

  pg-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: pg-pwd
      POSTGRES_USER: pg-user
      POSTGRES_DB: archive
    ports:
      - 5432:5432
