apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: prodms
  labels:
    app: postgres
data:
  POSTGRES_DB: archive
  POSTGRES_USER: pg-user
  POSTGRES_PASSWORD: pg-pwd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: prodms
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: prodms
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: prodms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim

# https://www.digitalocean.com/community/tutorials/how-to-deploy-postgres-to-kubernetes-cluster
# helm install test-release github-own-repo/prodms --set image.repository=docker.io/library/prodms-archive --set image.tag=1.1 --set replicaCount=3
# helm repo add github-own-repo https://yuryklimchuk.github.io/helm-charts
# helm repo list
# helm search repo github-own-repo

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: prodms
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres
