server.port=8300
spring.application.name = archive

# postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/archive-db
spring.datasource.username=db-user
spring.datasource.password=db-pass

# hibernate
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# discovery
#eureka.client.serviceUrl.defaultZone  = http://localhost:8761/eureka
#eureka.client.instance.preferIpAddress = true

