name: Microservice standard workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reuse:
    uses: YuryKlimchuk/prodms-workflows/.github/workflows/microservice-workflow-standard.yml@master
    secrets:
      TOKEN: ${{ secrets.TOKEN }}